language: java
script:
  - mvn clean verify --file ./simple-api/pom.xml
  - mvn clean verify org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=devopsorga20
  - cd ..

  #connect to docker hub
  - docker login -u $user -p $password

 #build
  - docker build -t $user/repo_simple_api:database database
  - docker build -t $user/repo_simple_api:httpd httpd
  - docker build -t $user/repo_simple_api:simple-api simple-api

  #images publication
  - docker push $user/repo_simple_api:database
  - docker push $user/repo_simple_api:httpd
  - docker push $user/repo_simple_api:simple-api
cache:
  directories:
    -$HOME/.m2

services:
  - docker


addons:
sonarcloud:
organization: "devopsorga20"
token: $sonarcloud_token




