language: java

stages:
  - cleaning maven
  - connecting
  - building
  - publishing

jobs:
  include:
    - stage: cleaning maven
      script:
        - mvn clean verify --file ./simple-api/pom.xml org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=apikey

    - stage: connecting
      script: docker login -u $user -p $password

    - stage: building
      script:
        - docker build -t $user/repo_simple_api:database database
        - docker build -t $user/repo_simple_api:httpd httpd
        - docker build -t $user/repo_simple_api:simple-api simple-api
        - docker push $user/repo_simple_api:database
        - docker push $user/repo_simple_api:httpd
        - docker push $user/repo_simple_api:simple-api


services:
  - docker


addons:
  sonarcloud:
    organization: "devopsorga20"
    token: $sonarcloud_token




