language: java
script:
  - mvn clean verify --file ./simple-api/pom.xml
  #connect to docker hub
  - docker login -u $user -p $password

 #build
  - docker build -t $user/repo_simple_api:database database
  - docker build -t $user/repo_simple_api:httpd httpd
  - docker build -t $user/repo_simple_api:simple-api simple-api

  #images publication
  - docker push $user/repo_simple_api:database
  - docker push $user/repo_simple_api:httpd
  - docker push $user/repo_simple_api:simple-api


